### ISSUE TITLE
Doesn't work for server worlds

### ISSUE THREAD

**Issue by K4sum1** [mitchts/nbt-converter#11]
I tried running the program with -r and it appeared to be doing something, but I loaded the world and it still crashes and has no entities.
I ran it exporting to a text file but it appears to have crashed. ~~python moment~~

`C:\Users\Admin\AppData\Local\Programs\Python\Python38>python.exe "F:\Docs\Downloads\nbt-converter-master\converter.py" "F:\Docs\Downloads\nbt-converter-master\test" -r > test.txt
Traceback (most recent call last):
  File "F:\Docs\Downloads\nbt-converter-master\converter.py", line 118, in <module>
    main(world, options)
  File "F:\Docs\Downloads\nbt-converter-master\converter.py", line 70, in main
    for chunk in region.iter_chunks():
  File "F:\Docs\Downloads\nbt-converter-master\nbt\region.py", line 484, in iter_chunks
    yield self.get_chunk(m.x, m.z)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\region.py", line 624, in get_chunk
    return self.get_nbt(x, z)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\region.py", line 601, in get_nbt
    nbt = NBTFile(buffer=data)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 641, in __init__
    self.parse_file()
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 670, in parse_file
    self._parse_buffer(self.file)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 414, in _parse_buffer
    self.tags.append(TAGLIST[self.tagID](buffer=buffer))
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 489, in __init__
    self._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 414, in _parse_buffer
    self.tags.append(TAGLIST[self.tagID](buffer=buffer))
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 489, in __init__
    self._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 506, in _parse_buffer
    tag._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 414, in _parse_buffer
    self.tags.append(TAGLIST[self.tagID](buffer=buffer))
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 355, in __init__
    self._parse_buffer(buffer)
  File "F:\Docs\Downloads\nbt-converter-master\nbt\nbt.py", line 363, in _parse_buffer
    self.value = read.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 32: invalid continuation byte`
[test.txt](https://github.com/mitchts/nbt-converter/files/11798843/test.txt)

**Comment by mitchts** [comment]
Can you please share the world file?

This isn't really intended for survival worlds which it sounds like this is.

**Comment by K4sum1** [comment]
It is a survival world, but I found Chunker and it worked (although I had to upload the worlds in batches).

It's NYA0 Phase 2 from here
https://snoopitek.com/nya/

**Comment by K4sum1** [comment]
least lazy github developer
